stages:
  - push_to_github

push_to_github_job:
  stage: push_to_github
  only:
    - deploy-to-github
  script:
        
    # set up Git configuration
    - echo "Configuring Git..."
    - git config --global user.email "${DEV_EMAIL}"
    - git config --global user.name "${DEV_NAME}"

    # add GitHub as a remote repository
    - echo "Adding GitHub remote..."
    - git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@${GITHUB_REPO_URL}

    # push changes to GitHub
    - echo "Pushing changes to GitHub..."
    - git push github HEAD:refs/heads/acmo-dev --force

  environment:
    name: production

  variables:
    GIT_STRATEGY: clone