targets:
  $default:
    builders:
      freezed:
        generate_for:
          exclude:
            - example/**
      json_serializable:
        generate_for:
          exclude:
            - example/**