name: tyrads_sdk
description: Show TyrAds offer wall.
version: 3.0.0-beta.0
homepage: https://github.com/tyrads-com/tyrads-sdk-flutter


environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  dio: ^5.4.2+1
  url_launcher: ^6.0.3
  cached_network_image: ^3.0.0
  pull_to_refresh: ^2.0.0
  readmore: ^3.0.0
  shared_preferences: ^2.0.5
  fluttertoast: ^8.0.9
  custom_timer: ^0.2.3
#  material_design_icons_flutter: ^7.0.7296
  google_fonts: ^6.2.0
  styled_text: ^8.1.0
  numeral: ^3.0.0
  back_button_interceptor: ^7.0.0
  platform_device_id_plus: ^1.0.7
  advertising_id: ^2.6.0
  #safe_device: ^1.1.4
  device_info_plus: ^11.3.0
  package_info_plus: ">=6.0.0 <9.0.0"
  #flutter_inappwebview: ^6.0.0
  flutter_security_checker: ^3.0.0
  image_picker: ^1.1.2
  http_parser: ^4.0.2
  usage_stats_new: ^2.0.6
  android_package_manager: ^0.7.1
  uuid: ^4.4.2
  webview_flutter: ^4.8.0
  slang: ^4.1.0
  slang_flutter: ^4.1.0
  connectivity_plus: ^6.1.1
  plugin_platform_interface: ^2.1.6
  awesome_select_plus: ^1.0.0
  marquee: ^2.2.3
  cryptography: ^2.7.0
  timelines_plus: ^1.0.4
  image_network: ^2.6.0
  pretty_qr_code: ^3.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  flutter_lints: ^4.0.0
  freezed: ^2.4.7
  ### flutter pub run build_runner build --delete-conflicting-outputs
  build_runner: ^2.4.8
  ### flutter packages pub run build_runner build
  flutter_gen_runner: ^5.2.0
  ### dart run build_runner build -d
  ### dart run slang
  slang_build_runner: ^4.1.0

flutter_gen:
  output: lib/src/gen/
  assets:
    outputs:
      package_parameter_enabled: true 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  plugin:
    platforms:
      android:
        package: com.tyrads.tyrads_sdk
        pluginClass: TyradsSdkPlugin

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
