// ignore_for_file: constant_identifier_names

import 'package:envied/envied.dart';

part 'env.g.dart';

@Envied()
abstract class Env {
  @EnviedField(varName: 'ANDROID_TYRREWARD_SDK_KEY')
  static const String ANDROID_TYRREWARD_SDK_KEY = _Env.ANDROID_TYRREWARD_SDK_KEY;

  @EnviedField(varName: 'ANDROID_TYRREWARD_SDK_SECRET')
  static const String ANDROID_TYRREWARD_SDK_SECRET = _Env.ANDROID_TYRREWARD_SDK_SECRET;

  @EnviedField(varName: 'ANDROID_TYRREWARD_SDK_ENC_KEY')
  static const String ANDROID_TYRREWARD_SDK_ENC_KEY = _Env.ANDROID_TYRREWARD_SDK_ENC_KEY;

  @EnviedField(varName: 'ANDROID_BELANDA1_TYRADS_SDK_KEY')
  static const String ANDROID_BELANDA1_TYRADS_SDK_KEY = _Env.ANDROID_BELANDA1_TYRADS_SDK_KEY;

  @EnviedField(varName: 'ANDROID_BELANDA1_TYRADS_SDK_SECRET')
  static const String ANDROID_BELANDA1_TYRADS_SDK_SECRET = _Env.ANDROID_BELANDA1_TYRADS_SDK_SECRET;

  @EnviedField(varName: 'ANDROID_BELANDA1_TYRADS_SDK_ENC_KEY')
  static const String ANDROID_BELANDA1_TYRADS_SDK_ENC_KEY = _Env.ANDROID_BELANDA1_TYRADS_SDK_ENC_KEY;

  @EnviedField(varName: 'ANDROID_BELANDA2_TYRADS_SDK_KEY')
  static const String ANDROID_BELANDA2_TYRADS_SDK_KEY = _Env.ANDROID_BELANDA2_TYRADS_SDK_KEY;

  @EnviedField(varName: 'ANDROID_BELANDA2_TYRADS_SDK_SECRET')
  static const String ANDROID_BELANDA2_TYRADS_SDK_SECRET = _Env.ANDROID_BELANDA2_TYRADS_SDK_SECRET;

  @EnviedField(varName: 'ANDROID_BELANDA2_TYRADS_SDK_ENC_KEY')
  static const String ANDROID_BELANDA2_TYRADS_SDK_ENC_KEY = _Env.ANDROID_BELANDA2_TYRADS_SDK_ENC_KEY;

  @EnviedField(varName: 'ANDROID_BELANDA3_TYRADS_SDK_KEY')
  static const String ANDROID_BELANDA3_TYRADS_SDK_KEY = _Env.ANDROID_BELANDA3_TYRADS_SDK_KEY;

  @EnviedField(varName: 'ANDROID_BELANDA3_TYRADS_SDK_SECRET')
  static const String ANDROID_BELANDA3_TYRADS_SDK_SECRET = _Env.ANDROID_BELANDA3_TYRADS_SDK_SECRET;

  @EnviedField(varName: 'ANDROID_BELANDA3_TYRADS_SDK_ENC_KEY')
  static const String ANDROID_BELANDA3_TYRADS_SDK_ENC_KEY = _Env.ANDROID_BELANDA3_TYRADS_SDK_ENC_KEY;

  @EnviedField(varName: 'IOS_TYRREWARD_SDK_KEY')
  static const String IOS_TYRREWARD_SDK_KEY = _Env.IOS_TYRREWARD_SDK_KEY;

  @EnviedField(varName: 'IOS_TYRREWARD_SDK_SECRET')
  static const String IOS_TYRREWARD_SDK_SECRET = _Env.IOS_TYRREWARD_SDK_SECRET;

  @EnviedField(varName: 'IOS_TYRREWARD_SDK_ENC_KEY')
  static const String IOS_TYRREWARD_SDK_ENC_KEY = _Env.IOS_TYRREWARD_SDK_ENC_KEY;

  @EnviedField(varName: 'IOS_BELANDA1_TYRADS_SDK_KEY')
  static const String IOS_BELANDA1_TYRADS_SDK_KEY = _Env.IOS_BELANDA1_TYRADS_SDK_KEY;

  @EnviedField(varName: 'IOS_BELANDA1_TYRADS_SDK_SECRET')
  static const String IOS_BELANDA1_TYRADS_SDK_SECRET = _Env.IOS_BELANDA1_TYRADS_SDK_SECRET;

  @EnviedField(varName: 'IOS_BELANDA1_TYRADS_SDK_ENC_KEY')
  static const String IOS_BELANDA1_TYRADS_SDK_ENC_KEY = _Env.IOS_BELANDA1_TYRADS_SDK_ENC_KEY;

  @EnviedField(varName: 'IOS_BELANDA2_TYRADS_SDK_KEY')
  static const String IOS_BELANDA2_TYRADS_SDK_KEY = _Env.IOS_BELANDA2_TYRADS_SDK_KEY;

  @EnviedField(varName: 'IOS_BELANDA2_TYRADS_SDK_SECRET')
  static const String IOS_BELANDA2_TYRADS_SDK_SECRET = _Env.IOS_BELANDA2_TYRADS_SDK_SECRET;

  @EnviedField(varName: 'IOS_BELANDA2_TYRADS_SDK_ENC_KEY')
  static const String IOS_BELANDA2_TYRADS_SDK_ENC_KEY = _Env.IOS_BELANDA2_TYRADS_SDK_ENC_KEY;

  @EnviedField(varName: 'IOS_BELANDA3_TYRADS_SDK_KEY')
  static const String IOS_BELANDA3_TYRADS_SDK_KEY = _Env.IOS_BELANDA3_TYRADS_SDK_KEY;

  @EnviedField(varName: 'IOS_BELANDA3_TYRADS_SDK_SECRET')
  static const String IOS_BELANDA3_TYRADS_SDK_SECRET = _Env.IOS_BELANDA3_TYRADS_SDK_SECRET;

  @EnviedField(varName: 'IOS_BELANDA3_TYRADS_SDK_ENC_KEY')
  static const String IOS_BELANDA3_TYRADS_SDK_ENC_KEY = _Env.IOS_BELANDA3_TYRADS_SDK_ENC_KEY;
}
